apiVersion: v2
appVersion: "2b26573"
description: >
  Helm chart to deploy PacketRusher service on Kubernetes.
home: https://github.com/gradiant/5g-charts
sources:
  - https://github.com/HewlettPackard/PacketRusher
maintainers:
  - email: alex@sengine.cloud
    name: impuls42
name: packetrusher
version: 0.0.6
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - gnb
  - ue
  - gradiant
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
