annotations:
  category: apps
  artifacthub.io/category: networking
apiVersion: v2
appVersion: 3.2.6
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: ueransim gNodeB for 5G RAN simulation
home: https://github.com/aligungr/UERANSIM
icon: https://github.com/aligungr/UERANSIM/raw/master/.github/logo.png
keywords:
  - network
  - apps
  - k8s
  - gradiant
maintainers:
  - email: alex@sengine.cloud
    name: impuls42
name: ueransim-gnb
sources:
  - https://github.com/aligungr/UERANSIM
version: 0.2.8
