apiVersion: v1
appVersion: "23.11"
description: >
  SRS epc
home: https://github.com/gradiant/5g-charts
sources:
  - https://github.com/srsran/srsRAN_4G
icon: https://docs.srsran.com/en/latest/_static/logo.png
maintainers:
  - email: alex@sengine.cloud
    name: impuls42
name: srs-epc
version: 0.2.2
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - epc
