{{ $open5gsName := default .Release.Name .Values.open5gsNameOverride }}

logger:
  level: {{ .Values.config.logLevel }}
parameter: {}
global:
sgwu:
  pfcp:
    server:
    - dev: "eth0"
    client:
      sgwc:
      - address: {{ default (printf "%s-sgwc-pfcp" $open5gsName) .Values.config.pfcp.client.sgwc.address }}
  gtpu:
    server:
    - dev:  {{ default "eth0" .Values.config.gtpu.server.dev }}
