apiVersion: v1
appVersion: "23.11"
description: srsRAN4g enodeb + ue.
home: https://github.com/sengine-cloud/gradiant-5g-charts
sources:
  - https://github.com/srsran/srsRAN_4G
icon: https://docs.srsran.com/en/latest/_static/logo.png
maintainers:
  - email: alex@sengine.cloud
    name: impuls42
name: srsran-4g-zmq
version: 0.2.0
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - lte
  - enodeb
