{{ $open5gsName := default .Release.Name .Values.open5gsNameOverride }}

logger:
  level: {{ .Values.config.logLevel }}
parameter: {}
global:
sgwc:
  gtpc:
    server:
    - dev: "eth0"
  pfcp:
    server:
    - dev: "eth0"
    client:
      sgwu:
      {{- range .Values.config.pfcp.client.sgwuList }}
      - address: {{ default (printf "%s-sgwu-pfcp" $open5gsName) .address }}
        apn: {{ .apn }}
      {{- end }}