apiVersion: v2
appVersion: "2.7.5"
description: >
  Helm chart to deploy Open5gs AMF service on Kubernetes.
home: https://github.com/sengine-cloud/gradiant-5g-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
  - email: alex@sengine.cloud
    name: impuls42
name: open5gs-amf
version: 2.3.5
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - ngc
  - gradiant
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
