dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  subscribers: []
  # Example:
  # subscribers:
  # - imsi: "999700000000001"
  #   ki: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  #   opc: "E8ED289DEBA952E4283B54E88E6183CA"
  #   apn: "internet"      # optional, default: internet
  #   sst: 1               # optional, default: 1
  #   sd: "000001"         # optional, default: 000001

# Common
mongodb:
  enabled: true
  auth:
    enabled: false
smf:
  enabled: true
  nameOverride: smf
upf:
  enabled: true
  nameOverride: upf
webui:
  enabled: true
  nameOverride: webui

# 4G
hss:
  enabled: true
  nameOverride: hss
  mongodb:
    enabled: false
mme:
  enabled: true
  nameOverride: mme
pcrf:
  enabled: true
  nameOverride: pcrf
  mongodb:
    enabled: false
sgwc:
  enabled: true
  nameOverride: sgwc
sgwu:
  enabled: true
  nameOverride: sgwu

# 5G
amf:
  enabled: true
  nameOverride: amf
ausf:
  enabled: true
  nameOverride: ausf
bsf:
  enabled: true
  nameOverride: bsf
nrf:
  enabled: true
  nameOverride: nrf
nssf:
  enabled: true
  nameOverride: nssf
pcf:
  enabled: true
  nameOverride: pcf
  mongodb:
    enabled: false
scp:
  enabled: true
  nameOverride: scp
  mongodb:
    enabled: false
sepp:
  enabled: true
  nameOverride: sepp
udm:
  enabled: true
  nameOverride: udm
udr:
  enabled: true
  nameOverride: udr
  mongodb:
    enabled: false
